version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=library
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 400M
    networks:
      - my-network
    volumes:
      - mongodb:/var/lib/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./scripts/mongosh.sh:/mongosh.sh

  lib-managment:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: lib-man-service
    ports:
      - "9000:9000"
    networks:
      - my-network

networks:
  my-network:
    name: my-network

volumes:
  mongodb:
    driver: local
