module.exports = {
  AUTHORIZATION_TOKEN: 'NoAuthTokenError',
  MISSING_PARAMETERS: 'MissingParamsError',
  NOT_ACCEPTABLE: 'NotAcceptable',
  NOT_FOUND: 'NotFound',
  FORBIDDEN: 'Forbidden',
  INVALID_VALUE: 'InvalidValue',
  BAD_REQUEST: 'BadRequest',
  CREDENTIALS_ERROR: 'CredentialsError',
  INVALID_EMAIL: 'ValidEmailError',
  DUPLICATE_EMAIL: 'DuplicateEmailError',
  DUPLICATE_USERNAME: 'DuplicateUsenameError',
  UNAUTHORIZED_ERROR: 'UnauthorizedError',
  DELETE_USER_UNRETURNED: 'DeleteUserUnreturned',
  CANT_CHANGE_ADMIN: 'CantChangeAdmin',
  USER_UPDATE_FAIL: 'UserUpdateFailed',
  COPIES_CHECKED_OUT: 'CopiesChekcedOut',
  CHECKOUT_OVERDUE: 'CheckoutOverdue',
  CHECKOUT_OR_RESERVED: 'CheckoutOrReserved',
  NO_COPIES_LEFT: 'NoCopiesLeft',
};
